"use client";
import{useEffect,useState}from"react";import QRCode from"qrcode";
const tf=["Before the pandemic, most people worked from home every day.","Many employees now have a hybrid work schedule.","Some companies hire people who live in different countries.","AI assistants can summarize meetings and translate conversations.","Employees no longer need to meet their colleagues in person.","AI translation is always completely accurate.","Companies may spend less money on office space and business travel.","Good companies expect their employees to be available 24/7."];
const mc=[["What is the main topic of the interview?","How to find a job","How people work in 2026","How to write a business report"],["What kind of schedule do many employees have?","A hybrid schedule","A night schedule","A seven-day schedule"],["Why do companies still use offices?","For storing computers","For teamwork, training, and building relationships","Because employees cannot work online"],["What can AI do during international meetings?","Hire new employees","Book office space","Provide captions and real-time translation"],["What is Chen Ming’s main message about technology?","It should help people work better.","It should replace every employee.","It should keep people online all the time."]];
const prep=["I’d like to welcome you ___ our program.","Today I’m talking ___ Chen Ming ___ his new book.","Before the pandemic, most people went ___ the office every day.","Many employees work ___ home on some days.","Team members may live ___ different countries.","AI can help employees ___ their reports.","Face-to-face communication is important ___ building relationships.","Some companies spend less money ___ office space and business travel.","Employees should switch ___ after work.","Technology should help people work better, not make them work ___ the time."];
const words=["welcome / I’d / program / our / you / like","talking / Chen Ming / his new book / I’m","home / employees / some days / work","countries / different / team members / live / may","useful / online meetings / international teams / are","help / reports / AI assistants / employees / can","important / communication / relationships / building / is","less money / companies / office space / may / spend","switch / employees / after work / should","people / technology / better / work / should / help"];
const notes=[["Work schedule","Many people have a ___ schedule."],["Work locations","Employees may work at home or in the ___."],["International teams","Some employees live in different ___."],["Online tools","Teams use video meetings and project-management ___."],["AI support","AI can summarize meetings and translate ___."],["Office activities","Offices are used for teamwork, training, and building ___."],["AI limitation","Real-time translation is not always ___."],["Possible savings","Companies may save money on office space and business ___."],["Work-life balance","Employees should switch off after ___." ]];
const script=[["Sora Kim","My name is Sora Kim, and I’d like to welcome you to our program. Today I’m talking to Chen Ming about his new book, The 2026 Workplace. Chen, tell us what the book is about."],["Chen Ming","Well, before the pandemic, most people went to the office every day. Then video meetings and cloud technology made remote work much more common."],["Sora Kim","And what is work like in 2026?"],["Chen Ming","It’s more flexible. Many people have a hybrid schedule: they work from home on some days and go to the office on others. Some companies also hire people who live in different countries."],["Sora Kim","How do these employees work together?"],["Chen Ming","They use online workspaces, video meetings, and project-management apps. AI assistants can summarize meetings, translate conversations, organize information, and help employees write reports."],["Sora Kim","Does that mean people don’t need to meet their colleagues in person?"],["Chen Ming","Not at all. Online tools are useful, but face-to-face communication is still important. Many companies use the office for teamwork, training, and building relationships."],["Sora Kim","What happens when team members speak different languages?"],["Chen Ming","AI can provide live captions and real-time translation during online meetings. It isn’t perfect, but it helps international teams communicate more easily."],["Sora Kim","That sounds convenient. Is it expensive?"],["Chen Ming","Some technology can be expensive, but companies may spend less on office space and business travel. They can also hire talented people from more locations."],["Sora Kim","But does flexible work mean that we have to be available 24/7?"],["Chen Ming","No. Good companies set clear working hours and encourage employees to switch off after work. Technology should help people work better—not make them work all the time."]];
const keys=[["A","1. False — Before the pandemic, most people went to the office every day. 2. True 3. True 4. True 5. False — Face-to-face communication is still important. 6. False — AI translation is useful, but it is not perfect. 7. True 8. False — Good companies set clear working hours and encourage employees to switch off after work."],["B","1. b　2. a　3. b　4. c　5. a"],["C","1. to　2. to; about　3. to　4. from　5. in　6. with　7. for　8. on　9. off　10. all"],["D","1. I’d like to welcome you to our program. 2. I’m talking to Chen Ming about his new book. 3. Employees work from home on some days. 4. Team members may live in different countries. 5. Online meetings are useful for international teams. 6. AI assistants can help employees with reports. 7. Communication is important for building relationships. 8. Companies may spend less money on office space. 9. Employees should switch off after work. 10. Technology should help people work better."],["E","1. hybrid　2. office　3. countries　4. apps　5. conversations　6. relationships　7. perfect　8. travel　9. work"]];
function Head(p:{l:string;t:string;n:string}){return <div className="head"><b>{p.l}</b><div><small>EXERCISE {p.l}</small><h2>{p.t}</h2><p>{p.n}</p></div></div>}
export default function Home(){const[sid,setSid]=useState(""),[draft,setDraft]=useState(""),[teacher,setTeacher]=useState(false),[code,setCode]=useState(""),[show,setShow]=useState({audio:false,script:false,key:false}),[qr,setQr]=useState(""),[a,setA]=useState<Record<string,string>>({}),[records,setRecords]=useState<Array<{studentId:string;enteredAt:string;submittedAt:string|null;progress:number}>>([]),[sending,setSending]=useState(false),[sent,setSent]=useState(false);useEffect(()=>{localStorage.removeItem("w26");QRCode.toDataURL(location.href.split("#")[0],{width:360,margin:2}).then(setQr)},[]);let put=(k:string,v:string)=>setA(x=>({...x,[k]:v}));let flip=(k:"audio"|"script"|"key")=>setShow(x=>({...x,[k]:!x[k]}));let progress=Math.min(100,Math.round(Object.values(a).filter(Boolean).length/42*100));let submitWork=async()=>{setSending(true);let r=await fetch("/api/submissions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({studentId:sid,action:"submit",progress,answers:a})});setSending(false);if(r.ok)setSent(true);else alert("送出失敗，請稍後再試")};let loadRecords=async()=>{let r=await fetch("/api/submissions?code="+encodeURIComponent(code));if(r.ok)setRecords((await r.json()).records||[])};let exportRecords=()=>{if(!records.length)return;let safe=(v:string)=>{let x=String(v??"");if(/^[=+@-]/.test(x))x="'"+x;return "\""+x.replaceAll("\"","\"\"")+"\""};let rows=[["學號","進入時間","送出時間","完成進度","狀態"],...records.map(r=>[r.studentId,new Date(r.enteredAt).toLocaleString("zh-TW"),r.submittedAt?new Date(r.submittedAt).toLocaleString("zh-TW"):"",r.progress+"%",r.submittedAt?"已送出":"尚未送出"])] as string[][];let blob=new Blob(["\uFEFF"+rows.map(row=>row.map(safe).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="workplace-student-history-"+new Date().toISOString().slice(0,10)+".csv";link.click();URL.revokeObjectURL(url)};if(!sid)return <main className="login"><section><b>W/26</b><p>BUSINESS ENGLISH · LISTENING LAB</p><h1>The 2026 Workplace</h1><form onSubmit={async e=>{e.preventDefault();let v=draft.trim();if(v){let r=await fetch("/api/submissions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({studentId:v,action:"enter"})});if(r.ok)setSid(v);else alert("目前無法進入，請稍後再試")}}}><label htmlFor="studentId">請輸入學號</label><input id="studentId" value={draft} onChange={e=>setDraft(e.target.value)} required autoFocus placeholder="Student ID" maxLength={30}/><button>進入課程 →</button></form><small>送出後，教師可查看您的學號、進入時間、完成進度與送出時間。每次開啟課程都需重新輸入學號。</small></section></main>;return <main>
<header id="top"><nav><a href="#top" className="brand"><b>W/26</b>Workplace Lab</a><div>{["A","B","C","D","E"].map(x=><a href={"#"+x} key={x}>{x}</a>)}<a href="#teacher">教師</a></div><div className="student">學號：{sid}<button onClick={()=>{setSid("")}}>變更</button></div></nav><div className="hero"><div><p className="eyebrow">BUSINESS ENGLISH · LISTENING LAB</p><h1>The <em>2026</em><br/>Workplace</h1><p className="lead">How hybrid teams, AI assistants, and human connection are reshaping the way we work.</p><a className="start" href="#A">開始學習 →</a></div><div className="visual"><i/><i/><b>AI<br/>＋<br/>HUMAN</b><span>HYBRID · GLOBAL · FLEXIBLE</span></div></div><div className="progress"><span>YOUR PROGRESS</span><i><b style={{width:progress+"%"}}/></i><strong>{progress}%</strong></div></header>
<section className="intro wrap"><p className="eyebrow">01 / LISTEN</p><div><h2>Listen for the <em>big picture.</em></h2><p>主持人 Sora Kim 訪問作者 Chen Ming，談論 2026 年的混合工作、國際團隊、AI 協作與工作生活平衡。</p></div></section>
{show.audio?<section className="audio wrap"><b>▶ The 2026 Workplace</b><audio controls src="/the-2026-workplace.mp3"/></section>:<p className="locked wrap">🔒 音檔目前由教師關閉</p>}
<section className="exercise wrap" id="A"><Head l="A" t="True or False" n="判斷敘述是否正確，並訂正錯誤敘述。"/>{tf.map((s,i)=><div className="row" key={s}><b>{String(i+1).padStart(2,"0")}</b><p>{s}</p><div>{["T","F"].map(v=><button className={a["a"+i]===v?"on":""} onClick={()=>put("a"+i,v)} key={v}>{v}</button>)}</div></div>)}</section>
<section className="dark" id="B"><div className="exercise wrap"><Head l="B" t="Choose the Best Answer" n="聆聽訪談，選出最適合的答案。"/><div className="cards">{mc.map((q,i)=><article key={q[0]}><small>QUESTION {i+1}</small><h3>{q[0]}</h3>{q.slice(1).map((o,j)=><button className={a["b"+i]===String(j)?"on":""} onClick={()=>put("b"+i,String(j))} key={o}><i>{String.fromCharCode(97+j)}</i>{o}</button>)}</article>)}</div></div></section>
<section className="exercise wrap" id="C"><Head l="C" t="Preposition Focus" n="再次聆聽，在空格中填入正確的介系詞。"/>{prep.map((q,i)=><label className="fill" key={q}><b>{i+1}</b><span>{q}</span><input value={a["c"+i]||""} onChange={e=>put("c"+i,e.target.value)} placeholder="type here"/></label>)}</section>
<section className="paper" id="D"><div className="exercise wrap"><Head l="D" t="Build the Sentence" n="重新排列字詞，並視需要加入介系詞。"/>{words.map((q,i)=><label className="order" key={q}><b>{String(i+1).padStart(2,"0")}</b><div><code>{q}</code><input value={a["d"+i]||""} onChange={e=>put("d"+i,e.target.value)} placeholder="Write the complete sentence…"/></div></label>)}</div></section>
<section className="exercise wrap" id="E"><Head l="E" t="Complete the Notes" n="每格填入一至兩個英文字。"/><div className="notes">{notes.map((n,i)=><label key={n[0]}><b>{n[0]}</b><span>{n[1]}</span><input value={a["e"+i]||""} onChange={e=>put("e"+i,e.target.value)}/></label>)}</div></section>
<section className="submitBox wrap"><p className="eyebrow">FINISH / 送出作答</p><h2>完成了嗎？</h2><p>目前完成進度：<b>{progress}%</b>。送出後教師即可查看您的學習紀錄。</p><button onClick={submitWork} disabled={sending||sent}>{sent?"✓ 已成功送出":sending?"送出中…":"送出作答 →"}</button><button className="clearWork" onClick={()=>{if(confirm("確定要清除目前所有作答嗎？")){setA({});setSent(false);localStorage.removeItem("w26")}}}>清除我的作答</button></section>{show.script&&<section className="reveal wrap"><p className="eyebrow">SCRIPT / 逐字稿</p><h2>Listen. Read. <em>Notice.</em></h2><div className="script">{script.map((r,i)=><p key={i}><b>{r[0]}</b>{r[1]}</p>)}</div></section>}
{show.key&&<section className="answers wrap"><p className="eyebrow">ANSWER KEY / 解答</p><h2>Check your <em>work.</em></h2>{keys.map(x=><details key={x[0]}><summary>Exercise {x[0]} <b>＋</b></summary><p>{x[1]}</p></details>)}</section>}
<section className="teacher" id="teacher"><div className="wrap teachergrid"><div><p className="eyebrow">TEACHER CONTROL</p><h2>教師控制台</h2><p>音檔、逐字稿與解答預設為關閉。教師可使用控制碼進入，再依課程進度分別開放。</p>{!teacher?<form onSubmit={e=>{e.preventDefault();code==="2026"?(setTeacher(true),loadRecords()):alert("控制碼不正確")}}><input type="password" value={code} onChange={e=>setCode(e.target.value)} placeholder="輸入教師控制碼"/><button>解鎖控制台</button></form>:<div className="controls">{[["audio","MP3 播放器"],["script","Listening Script"],["key","Answer Key"]].map(x=><button key={x[0]} className={show[x[0] as keyof typeof show]?"on":""} onClick={()=>flip(x[0] as "audio"|"script"|"key")}><i/>{x[1]}<b>{show[x[0] as keyof typeof show]?"已開啟":"已關閉"}</b></button>)}<button onClick={loadRecords}>重新整理學生紀錄</button><button onClick={exportRecords} disabled={!records.length}>匯出學生歷程 CSV</button><button onClick={()=>setTeacher(false)}>鎖定控制台</button></div>} {teacher&&<div className="records"><h3>學生學習紀錄</h3>{records.length===0?<p>目前尚無紀錄。</p>:<div className="recordTable">{records.map(r=><div key={r.studentId}><b>{r.studentId}</b><span>進入：{new Date(r.enteredAt).toLocaleString("zh-TW")}</span><span>{r.submittedAt?"已送出 · "+r.progress+"%":"尚未送出"}</span></div>)}</div>}</div>}</div><div className="qr"><small>SCAN TO LEARN</small>{qr&&<img src={qr} alt="課程 QR code"/>}<b>課程 QR CODE</b><span>使用手機相機掃描，立即開啟課程</span></div></div></section><footer><b>W/26</b><span>The 2026 Workplace · Interactive Listening Course</span><a href="#top">回到頂端 ↑</a></footer></main>}







