import {withCors,preflight} from "../cors";
import{desc,eq}from"drizzle-orm";import{getDb}from"../../../db";import{submissions}from"../../../db/schema";
async function handlePOST(request:Request){try{const p=await request.json() as{studentId?:string;action?:string;progress?:number;answers?:Record<string,string>};const studentId=(p.studentId||"").trim().slice(0,30);if(!studentId)return Response.json({error:"studentId is required"},{status:400});const now=new Date().toISOString(),db=getDb(),existing=await db.select().from(submissions).where(eq(submissions.studentId,studentId)).limit(1);if(existing.length){await db.update(submissions).set(p.action==="submit"?{submittedAt:now,progress:Math.max(0,Math.min(100,p.progress||0)),answers:JSON.stringify(p.answers||{})}:{enteredAt:now}).where(eq(submissions.studentId,studentId))}else{await db.insert(submissions).values({studentId,enteredAt:now,submittedAt:p.action==="submit"?now:null,progress:p.action==="submit"?(p.progress||0):0,answers:p.action==="submit"?JSON.stringify(p.answers||{}):"{}"})}return Response.json({ok:true})}catch{return Response.json({error:"Unable to save record"},{status:500})}}
async function handleGET(request:Request){const code=new URL(request.url).searchParams.get("code");if(code!=="2026")return Response.json({error:"Unauthorized"},{status:401});try{const rows=await getDb().select({studentId:submissions.studentId,enteredAt:submissions.enteredAt,submittedAt:submissions.submittedAt,progress:submissions.progress,answers:submissions.answers}).from(submissions).orderBy(desc(submissions.enteredAt)).limit(1000);return Response.json({records:rows.map(row=>{let answers:Record<string,string>={};try{answers=JSON.parse(row.answers||"{}")}catch{}return{studentId:row.studentId,enteredAt:row.enteredAt,submittedAt:row.submittedAt,progress:row.progress,answerCount:Object.values(answers).filter(Boolean).length}})})}catch{return Response.json({error:"Unable to load records"},{status:500})}}


export const GET=withCors(handleGET);
export const POST=withCors(handlePOST);
export const OPTIONS=preflight;
