import{desc}from"drizzle-orm";import{getDb}from"../../../db";import{submissions}from"../../../db/schema";
const answerColumns=[...Array.from({length:8},(_,i)=>`a${i}`),...Array.from({length:5},(_,i)=>`b${i}`),...Array.from({length:10},(_,i)=>`c${i}`),...Array.from({length:10},(_,i)=>`d${i}`),...Array.from({length:9},(_,i)=>`e${i}`)];
const label=(key:string)=>key[0].toUpperCase()+String(Number(key.slice(1))+1);
const xml=(value:unknown)=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]!));
const safe=(value:unknown)=>{const text=String(value??"");return/^[=+@-]/.test(text)?"'"+text:text};
const twTime=(value:string|null)=>value?new Intl.DateTimeFormat("zh-TW",{timeZone:"Asia/Taipei",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date(value)):"";
const cell=(value:unknown,style="Cell")=>`<Cell ss:StyleID="${style}"><Data ss:Type="String">${xml(safe(value))}</Data></Cell>`;
const row=(values:unknown[],style="Cell")=>`<Row>${values.map(v=>cell(v,style)).join("")}</Row>`;
const sheet=(name:string,rows:string,widths:number[])=>`<Worksheet ss:Name="${xml(name)}"><Table>${widths.map(w=>`<Column ss:Width="${w}"/>`).join("")}${rows}</Table><WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel"><FreezePanes/><FrozenNoSplit/><SplitHorizontal>1</SplitHorizontal><TopRowBottomPane>1</TopRowBottomPane></WorksheetOptions></Worksheet>`;
async function makeWorkbook(){const records=await getDb().select().from(submissions).orderBy(desc(submissions.enteredAt)).limit(1000);const summary=[row(["學號","進入時間（臺北）","送出時間（臺北）","完成進度","狀態","已作答題數"],"Header"),...records.map(r=>{let answers:Record<string,string>={};try{answers=JSON.parse(r.answers||"{}")}catch{}return row([r.studentId,twTime(r.enteredAt),twTime(r.submittedAt),`${r.progress}%`,r.submittedAt?"已送出":"尚未送出",Object.values(answers).filter(Boolean).length])})].join("");const detail=[row(["學號",...answerColumns.map(label),"原始作答資料"],"Header"),...records.map(r=>{let answers:Record<string,string>={};try{answers=JSON.parse(r.answers||"{}")}catch{}return row([r.studentId,...answerColumns.map(k=>answers[k]||""),r.answers||"{}"])})].join("");const info=[row(["匯出項目","內容"],"Header"),row(["課程名稱","The 2026 Workplace"]),row(["匯出時間（臺北）",twTime(new Date().toISOString())]),row(["學生紀錄數",records.length]),row(["說明","學生總覽包含進入與送出狀態；作答明細保留各題答案與原始資料。"])].join("");return`<?xml version="1.0"?><?mso-application progid="Excel.Sheet"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Cell"><Alignment ss:Vertical="Center"/><Font ss:FontName="Arial" ss:Size="10"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#D9E2DF"/></Borders></Style><Style ss:ID="Header"><Alignment ss:Vertical="Center" ss:WrapText="1"/><Font ss:FontName="Arial" ss:Size="10" ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#143D3B" ss:Pattern="Solid"/></Style></Styles>${sheet("學生總覽",summary,[90,145,145,80,85,90])}${sheet("作答明細",detail,[90,...answerColumns.map(()=>70),260])}${sheet("匯出說明",info,[150,480])}</Workbook>`}
function fileName(){return`The-2026-Workplace-學生資料-${new Date().toISOString().slice(0,10)}.xls`}
function authorized(request:Request){return new URL(request.url).searchParams.get("code")==="2026"}
export async function GET(request:Request){if(!authorized(request))return Response.json({error:"教師驗證失敗"},{status:401});return new Response(await makeWorkbook(),{headers:{"content-type":"application/vnd.ms-excel; charset=utf-8","content-disposition":`attachment; filename*=UTF-8''${encodeURIComponent(fileName())}`,"cache-control":"no-store"}})}
export async function POST(request:Request){if(!authorized(request))return Response.json({error:"教師驗證失敗"},{status:401});const uploadUrl=process.env.GOOGLE_DRIVE_UPLOAD_URL,secret=process.env.GOOGLE_DRIVE_UPLOAD_SECRET;if(!uploadUrl||!secret)return Response.json({error:"Google Drive 尚未完成一次性授權設定"},{status:503});const body=await makeWorkbook(),name=fileName();const result=await fetch(uploadUrl,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({secret,fileName:name,mimeType:"application/vnd.ms-excel",content:btoa(unescape(encodeURIComponent(body)))})});const text=await result.text();if(!result.ok)return Response.json({error:"Google Drive 上傳失敗"},{status:502});try{return Response.json(JSON.parse(text))}catch{return Response.json({ok:true,message:text})}}

